# Generated by Django 5.2.7 on 2026-05-14 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('is_up', models.BooleanField(default=False)),
                ('load_time', models.FloatField(blank=True, null=True)),
                ('ttfb', models.FloatField(blank=True, null=True)),
                ('page_size_kb', models.FloatField(blank=True, null=True)),
                ('perf_rating', models.CharField(blank=True, max_length=20)),
                ('performance_score', models.IntegerField(blank=True, null=True)),
                ('seo_score', models.IntegerField(blank=True, null=True)),
                ('security_score', models.IntegerField(blank=True, null=True)),
                ('overall_score', models.IntegerField(blank=True, null=True)),
                ('page_title', models.TextField(blank=True)),
                ('meta_description', models.TextField(blank=True)),
                ('is_https', models.BooleanField(default=False)),
                ('has_ssl', models.BooleanField(default=False)),
                ('check_data', models.TextField(blank=True)),
                ('errors_data', models.TextField(blank=True)),
                ('seo_data', models.TextField(blank=True)),
                ('performance_data', models.TextField(blank=True)),
                ('security_data', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-analyzed_at'],
                'indexes': [models.Index(fields=['url', '-analyzed_at'], name='monitor_ana_url_21baaa_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlertHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('ok', 'OK'), ('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=20)),
                ('message', models.TextField()),
                ('category', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_records', to='monitor.analysisreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
