"""
Django settings for webmonitor project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ez(s=x%m(trzq%5+kod*2zb0h%&tp2!h)vrp4dp*@@dz0@@pr_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'monitor',
    'corsheaders',
    
]


MIDDLEWARE = [

    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'webmonitor.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'webmonitor.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'frontend' / 'build' / 'static',
]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CORS_ALLOW_ALL_ORIGINS = True



# --- Email / alert defaults -------------------------------------------------
# Load persistent SRE settings if configured via the UI
import json
sre_settings_path = BASE_DIR / 'sre_settings.json'
sre_config = {}
if sre_settings_path.exists():
    try:
        with open(sre_settings_path, 'r', encoding='utf-8') as f:
            sre_config = json.load(f)
    except Exception:
        pass

# Configure `ALERT_EMAIL_RECIPIENTS` in your environment or local settings to enable.
raw_recipients = sre_config.get("alert_email_recipients") or os.environ.get("ALERT_EMAIL_RECIPIENTS", "")
if isinstance(raw_recipients, list):
    ALERT_EMAIL_RECIPIENTS = [r.strip() for r in raw_recipients if r.strip()]
else:
    ALERT_EMAIL_RECIPIENTS = [r.strip() for r in raw_recipients.split(",") if r.strip()]

EMAIL_HOST_USER = sre_config.get("email_host_user") or os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = sre_config.get("email_host_password") or os.environ.get("EMAIL_HOST_PASSWORD", "")

EMAIL_FROM = EMAIL_HOST_USER if EMAIL_HOST_USER else os.environ.get("EMAIL_FROM", "monitor@example.com")
DEFAULT_FROM_EMAIL = EMAIL_FROM

# Automatically switch to SMTP backend if real SMTP credentials are provided
if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
else:
    EMAIL_BACKEND = os.environ.get(
        "EMAIL_BACKEND",
        "django.core.mail.backends.console.EmailBackend" if DEBUG else "django.core.mail.backends.smtp.EmailBackend",
    )

# SRE Proactive auto-configuration helper for real Gmail accounts
is_gmail = "@gmail.com" in EMAIL_HOST_USER.lower()

EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.gmail.com" if is_gmail else "")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587" if is_gmail else "0")) if os.environ.get("EMAIL_PORT") or is_gmail else None
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "True" if is_gmail else "False").lower() in ("1", "true", "yes")
